application:
  name: engidone-auth
  version: 1.0.0
  server:
    port: 3000
logging: console
database:
  dsn: "{engine}://{user}:{password}@{host}:{port}/{db_name}?sslmode={ssl_mode}"
  engine: postgres
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  host: ${DB_HOST}
  port: ${DB_PORT}
  ssl_mode: ${DB_SSL_MODE}
  db_name: ${DB_NAME}
certs:
  public: keys/public_key.pem
  private: keys/private_key.pem