# Build stage
FROM golang:1.25.1-alpine

WORKDIR /app

# Install required packages for PostgreSQL
RUN apk add --no-cache gcc musl-dev make

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY . .

RUN echo ${pwd}
# Expose port 9000
EXPOSE 3000

# Run the binary
CMD ["make", "dev"]