// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error
	DeleteUser(ctx context.Context, db DBTX, id int32) error
	GetUserByEmail(ctx context.Context, db DBTX, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, db DBTX, id int32) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, db DBTX, username string) (GetUserByUsernameRow, error)
	ListUsers(ctx context.Context, db DBTX) ([]ListUsersRow, error)
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) error
	VerifyCredentials(ctx context.Context, db DBTX, arg VerifyCredentialsParams) (VerifyCredentialsRow, error)
}

var _ Querier = (*Queries)(nil)
