// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: internal/hello/proto/hello.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hello request message
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_internal_hello_proto_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hello_proto_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_internal_hello_proto_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Hello response message
type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_internal_hello_proto_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hello_proto_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_internal_hello_proto_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_hello_proto_hello_proto protoreflect.FileDescriptor

const file_internal_hello_proto_hello_proto_rawDesc = "" +
	"\n" +
	" internal/hello/proto/hello.proto\x12\x05hello\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"C\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2B\n" +
	"\fHelloService\x122\n" +
	"\x05Hello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponseB$Z\"engidone-auth/internal/hello/protob\x06proto3"

var (
	file_internal_hello_proto_hello_proto_rawDescOnce sync.Once
	file_internal_hello_proto_hello_proto_rawDescData []byte
)

func file_internal_hello_proto_hello_proto_rawDescGZIP() []byte {
	file_internal_hello_proto_hello_proto_rawDescOnce.Do(func() {
		file_internal_hello_proto_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_hello_proto_hello_proto_rawDesc), len(file_internal_hello_proto_hello_proto_rawDesc)))
	})
	return file_internal_hello_proto_hello_proto_rawDescData
}

var file_internal_hello_proto_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_hello_proto_hello_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: hello.HelloRequest
	(*HelloResponse)(nil), // 1: hello.HelloResponse
}
var file_internal_hello_proto_hello_proto_depIdxs = []int32{
	0, // 0: hello.HelloService.Hello:input_type -> hello.HelloRequest
	1, // 1: hello.HelloService.Hello:output_type -> hello.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_hello_proto_hello_proto_init() }
func file_internal_hello_proto_hello_proto_init() {
	if File_internal_hello_proto_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_hello_proto_hello_proto_rawDesc), len(file_internal_hello_proto_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_hello_proto_hello_proto_goTypes,
		DependencyIndexes: file_internal_hello_proto_hello_proto_depIdxs,
		MessageInfos:      file_internal_hello_proto_hello_proto_msgTypes,
	}.Build()
	File_internal_hello_proto_hello_proto = out.File
	file_internal_hello_proto_hello_proto_goTypes = nil
	file_internal_hello_proto_hello_proto_depIdxs = nil
}
