// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Credential struct {
	ID        int32
	UserID    uuid.UUID
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RecoveryCode struct {
	ID        int32
	UserID    uuid.UUID
	Code      string
	IsValid   bool
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	ID           int32
	UserID       uuid.UUID
	RefreshToken string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
