// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const existsRefreshToken = `-- name: ExistsRefreshToken :one
SELECT EXISTS(
  SELECT 1
  FROM refresh_tokens
  WHERE user_id = $1 AND refresh_token = $2
) AS exists
`

type ExistsRefreshTokenParams struct {
	UserID       uuid.UUID
	RefreshToken string
}

func (q *Queries) ExistsRefreshToken(ctx context.Context, arg ExistsRefreshTokenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsRefreshToken, arg.UserID, arg.RefreshToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCredential = `-- name: GetCredential :one
SELECT id, user_id, password, created_at, updated_at FROM credentials WHERE user_id = $1 AND password = $2
`

type GetCredentialParams struct {
	UserID   uuid.UUID
	Password string
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, arg.UserID, arg.Password)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecoveryCode = `-- name: GetRecoveryCode :one
SELECT code FROM recovery_codes WHERE code = $1 AND is_valid = TRUE AND expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) GetRecoveryCode(ctx context.Context, code string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryCode, code)
	err := row.Scan(&code)
	return code, err
}

const insertCredential = `-- name: InsertCredential :one
INSERT INTO credentials (user_id, password) VALUES ($1, $2) RETURNING id, user_id, password, created_at, updated_at
`

type InsertCredentialParams struct {
	UserID   uuid.UUID
	Password string
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, insertCredential, arg.UserID, arg.Password)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrUpdateRefreshToken = `-- name: InsertOrUpdateRefreshToken :one
INSERT INTO refresh_tokens (user_id, refresh_token)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
    refresh_token = EXCLUDED.refresh_token
RETURNING id, user_id, refresh_token, created_at, updated_at
`

type InsertOrUpdateRefreshTokenParams struct {
	UserID       uuid.UUID
	RefreshToken string
}

func (q *Queries) InsertOrUpdateRefreshToken(ctx context.Context, arg InsertOrUpdateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, insertOrUpdateRefreshToken, arg.UserID, arg.RefreshToken)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :one
INSERT INTO recovery_codes (user_id, code, is_valid, expires_at) VALUES ($1, $2, $3, $4) RETURNING id, user_id, code, is_valid, expires_at, created_at
`

type InsertRecoveryCodeParams struct {
	UserID    uuid.UUID
	Code      string
	IsValid   bool
	ExpiresAt time.Time
}

type InsertRecoveryCodeRow struct {
	ID        int32
	UserID    uuid.UUID
	Code      string
	IsValid   bool
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) (InsertRecoveryCodeRow, error) {
	row := q.db.QueryRowContext(ctx, insertRecoveryCode,
		arg.UserID,
		arg.Code,
		arg.IsValid,
		arg.ExpiresAt,
	)
	var i InsertRecoveryCodeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.IsValid,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many

SELECT id, user_id, password, created_at, updated_at FROM credentials
`

// queries.sql
func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE credentials
SET password = $1, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $2
`

type UpdatePasswordParams struct {
	Password string
	UserID   uuid.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.UserID)
	return err
}
